// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_upload_evidence_api_v1_upload__post
 */
export type BodyUploadEvidenceApiV1UploadPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * File Category
     */
    file_category: string;
    /**
     * Specific Type
     */
    specific_type: string;
};

/**
 * DemoRequest
 */
export type DemoRequest = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Company
     */
    company: string;
};

/**
 * DemoRequestStatusUpdate
 */
export type DemoRequestStatusUpdate = {
    /**
     * Status
     */
    status: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ShopRegistrationPayload
 */
export type ShopRegistrationPayload = {
    /**
     * Name
     */
    name: string;
    /**
     * Owner Name
     */
    owner_name: string;
    /**
     * Mobile
     */
    mobile: string;
    /**
     * Address
     */
    address: string;
    /**
     * City
     */
    city: string;
    /**
     * State
     */
    state: string;
    /**
     * Category
     */
    category: string;
    /**
     * Years In Business
     */
    years_in_business: number;
    /**
     * Monthly Sales
     */
    monthly_sales: number;
    /**
     * Requested Loan
     */
    requested_loan: number;
    /**
     * Loan Purpose
     */
    loan_purpose: string;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadUserMeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type ReadUserMeApiV1AuthMeGetResponses = {
    /**
     * Response Read User Me Api V1 Auth Me Get
     *
     * Successful Response
     */
    200: unknown;
};

export type RegisterShopApiV1ShopsRegisterPostData = {
    body: ShopRegistrationPayload;
    path?: never;
    query?: never;
    url: '/api/v1/shops/register';
};

export type RegisterShopApiV1ShopsRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterShopApiV1ShopsRegisterPostError = RegisterShopApiV1ShopsRegisterPostErrors[keyof RegisterShopApiV1ShopsRegisterPostErrors];

export type RegisterShopApiV1ShopsRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetUserShopsApiV1ShopsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/shops/';
};

export type GetUserShopsApiV1ShopsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserShopsApiV1ShopsGetError = GetUserShopsApiV1ShopsGetErrors[keyof GetUserShopsApiV1ShopsGetErrors];

export type GetUserShopsApiV1ShopsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetShopApiV1ShopsShopIdGetData = {
    body?: never;
    path: {
        /**
         * Shop Id
         */
        shop_id: string;
    };
    query?: never;
    url: '/api/v1/shops/{shop_id}';
};

export type GetShopApiV1ShopsShopIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShopApiV1ShopsShopIdGetError = GetShopApiV1ShopsShopIdGetErrors[keyof GetShopApiV1ShopsShopIdGetErrors];

export type GetShopApiV1ShopsShopIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateShopApiV1ShopsShopIdPutData = {
    /**
     * Payload
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Shop Id
         */
        shop_id: string;
    };
    query?: never;
    url: '/api/v1/shops/{shop_id}';
};

export type UpdateShopApiV1ShopsShopIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateShopApiV1ShopsShopIdPutError = UpdateShopApiV1ShopsShopIdPutErrors[keyof UpdateShopApiV1ShopsShopIdPutErrors];

export type UpdateShopApiV1ShopsShopIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadEvidenceApiV1UploadPostData = {
    body: BodyUploadEvidenceApiV1UploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/upload/';
};

export type UploadEvidenceApiV1UploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadEvidenceApiV1UploadPostError = UploadEvidenceApiV1UploadPostErrors[keyof UploadEvidenceApiV1UploadPostErrors];

export type UploadEvidenceApiV1UploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerAnalysisApiV1AnalysisTriggerApplicationIdPostData = {
    body?: never;
    path: {
        /**
         * Application Id
         */
        application_id: string;
    };
    query?: never;
    url: '/api/v1/analysis/trigger/{application_id}';
};

export type TriggerAnalysisApiV1AnalysisTriggerApplicationIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerAnalysisApiV1AnalysisTriggerApplicationIdPostError = TriggerAnalysisApiV1AnalysisTriggerApplicationIdPostErrors[keyof TriggerAnalysisApiV1AnalysisTriggerApplicationIdPostErrors];

export type TriggerAnalysisApiV1AnalysisTriggerApplicationIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetApplicationReportApiV1ReportApplicationIdGetData = {
    body?: never;
    path: {
        /**
         * Application Id
         */
        application_id: string;
    };
    query?: never;
    url: '/api/v1/report/{application_id}';
};

export type GetApplicationReportApiV1ReportApplicationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApplicationReportApiV1ReportApplicationIdGetError = GetApplicationReportApiV1ReportApplicationIdGetErrors[keyof GetApplicationReportApiV1ReportApplicationIdGetErrors];

export type GetApplicationReportApiV1ReportApplicationIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSystemStatusApiV1SystemStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/status';
};

export type GetSystemStatusApiV1SystemStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubmitDemoRequestApiV1SystemDemoRequestsPostData = {
    body: DemoRequest;
    path?: never;
    query?: never;
    url: '/api/v1/system/demo-requests';
};

export type SubmitDemoRequestApiV1SystemDemoRequestsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitDemoRequestApiV1SystemDemoRequestsPostError = SubmitDemoRequestApiV1SystemDemoRequestsPostErrors[keyof SubmitDemoRequestApiV1SystemDemoRequestsPostErrors];

export type SubmitDemoRequestApiV1SystemDemoRequestsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDashboardStatsApiV1AdminDashboardStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/dashboard-stats';
};

export type GetDashboardStatsApiV1AdminDashboardStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAuditLogsApiV1AdminAuditLogsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/audit-logs';
};

export type GetAuditLogsApiV1AdminAuditLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAuditLogsApiV1AdminAuditLogsGetError = GetAuditLogsApiV1AdminAuditLogsGetErrors[keyof GetAuditLogsApiV1AdminAuditLogsGetErrors];

export type GetAuditLogsApiV1AdminAuditLogsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllUsersApiV1AdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/users';
};

export type GetAllUsersApiV1AdminUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllUsersApiV1AdminUsersGetError = GetAllUsersApiV1AdminUsersGetErrors[keyof GetAllUsersApiV1AdminUsersGetErrors];

export type GetAllUsersApiV1AdminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllApplicationsApiV1AdminApplicationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/applications';
};

export type GetAllApplicationsApiV1AdminApplicationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllApplicationsApiV1AdminApplicationsGetError = GetAllApplicationsApiV1AdminApplicationsGetErrors[keyof GetAllApplicationsApiV1AdminApplicationsGetErrors];

export type GetAllApplicationsApiV1AdminApplicationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllNotificationsApiV1AdminNotificationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/notifications';
};

export type GetAllNotificationsApiV1AdminNotificationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllNotificationsApiV1AdminNotificationsGetError = GetAllNotificationsApiV1AdminNotificationsGetErrors[keyof GetAllNotificationsApiV1AdminNotificationsGetErrors];

export type GetAllNotificationsApiV1AdminNotificationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MarkNotificationAsReadApiV1AdminNotificationsNotifIdReadPostData = {
    body?: never;
    path: {
        /**
         * Notif Id
         */
        notif_id: string;
    };
    query?: never;
    url: '/api/v1/admin/notifications/{notif_id}/read';
};

export type MarkNotificationAsReadApiV1AdminNotificationsNotifIdReadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkNotificationAsReadApiV1AdminNotificationsNotifIdReadPostError = MarkNotificationAsReadApiV1AdminNotificationsNotifIdReadPostErrors[keyof MarkNotificationAsReadApiV1AdminNotificationsNotifIdReadPostErrors];

export type MarkNotificationAsReadApiV1AdminNotificationsNotifIdReadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MarkAllNotificationsAsReadApiV1AdminNotificationsReadAllPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/notifications/read-all';
};

export type MarkAllNotificationsAsReadApiV1AdminNotificationsReadAllPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllDemoRequestsApiV1AdminDemoRequestsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/demo-requests';
};

export type GetAllDemoRequestsApiV1AdminDemoRequestsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllDemoRequestsApiV1AdminDemoRequestsGetError = GetAllDemoRequestsApiV1AdminDemoRequestsGetErrors[keyof GetAllDemoRequestsApiV1AdminDemoRequestsGetErrors];

export type GetAllDemoRequestsApiV1AdminDemoRequestsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateDemoRequestStatusApiV1AdminDemoRequestsReqIdPatchData = {
    body: DemoRequestStatusUpdate;
    path: {
        /**
         * Req Id
         */
        req_id: string;
    };
    query?: never;
    url: '/api/v1/admin/demo-requests/{req_id}';
};

export type UpdateDemoRequestStatusApiV1AdminDemoRequestsReqIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDemoRequestStatusApiV1AdminDemoRequestsReqIdPatchError = UpdateDemoRequestStatusApiV1AdminDemoRequestsReqIdPatchErrors[keyof UpdateDemoRequestStatusApiV1AdminDemoRequestsReqIdPatchErrors];

export type UpdateDemoRequestStatusApiV1AdminDemoRequestsReqIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSecureDocumentUrlApiV1DocumentsDocumentIdUrlGetData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/url';
};

export type GetSecureDocumentUrlApiV1DocumentsDocumentIdUrlGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSecureDocumentUrlApiV1DocumentsDocumentIdUrlGetError = GetSecureDocumentUrlApiV1DocumentsDocumentIdUrlGetErrors[keyof GetSecureDocumentUrlApiV1DocumentsDocumentIdUrlGetErrors];

export type GetSecureDocumentUrlApiV1DocumentsDocumentIdUrlGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
